#!/bin/bash

session=$(find ~/projects ~/.config -mindepth 1 -maxdepth 1 -type d | fzf)

if [ -z "$session" ]; then
    exit 0
fi

window_name=$(basename "$session" | tr . _)

tmux new-window -n "$window_name" -c "$session"

